### ISSUE TITLE
Market update failure on bad data killing process_messages thread

### ISSUE THREAD

**Issue by Tromador** [eyeonus/EDDBlink-listener#15]
```
Market update for SEMALI/RASCH HUB finished in 0.516 seconds.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "S:\Elite Dangerous Programs\Trade Dangerous\eddblink_listener.py", line 649, in process_messages
    curs.executemany(insStmt, itemList)
sqlite3.IntegrityError: UNIQUE constraint failed: StationItem.station_id, StationItem.item_id
```

**Comment by Tromador** [comment]
https://github.com/bgol wrote:

It was EDDI https://ross.eddb.io/eddn/log/75839746
HeliostaticFurnaces is listed twice.

EDDI does send wrong commodity messages since 3.0.1-X. They only corrected it
recently with version 3.0.1-rc5 I think. EDDB has it blacklisted.

That's the downside of the executemany. In my own code I keep track of the IDs
and throw a warning if a item comes more than one time, eg:

```
python
unqItems = set()
for commodity in commodities:
     ...
     if item_id in unqItems:
         if config['verbose']:
             print("Multiple item '" + itemName + "'")
         continue
     unqItems.add(item_id)
     ....
```

**Comment by Tromador** [comment]
Firstly we can blacklist EDDI in the existing config. Once they finish a new release with it fixed, if we want we can allow it with a minimum version requirement. So that's an easy fix.

That said, I think we should code an exception so that if a market update is bad, then process_messages can ignore (or log or dump) the bad batch of data and still carry on with the next entry in the queue.

**Comment by Tromador** [comment]
Not seen any more problems like this, closing.
