### ISSUE TITLE
Coriolis problem upstream

### ISSUE THREAD

**Issue by Tromador** [eyeonus/EDDBlink-listener#21]
```
NOTE: Requesting https://raw.githubusercontent.com/EDCD/coriolis-data/master/dist/index.json
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/elite/.local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/elite/.local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./eddblink_listener.py", line 372, in check_update
    trade.main(('trade.py', 'import', '-P', 'eddblink', '-O', options))
  File "/home/elite/.local/lib/python3.7/site-packages/tradedangerous/cli.py", line 70, in main
    trade(argv)
  File "/home/elite/.local/lib/python3.7/site-packages/tradedangerous/cli.py", line 125, in trade
    results = cmdenv.run(tdb)
  File "/home/elite/.local/lib/python3.7/site-packages/tradedangerous/commands/commandenv.py", line 81, in run
    return self._cmd.run(results, self, tdb)
  File "/home/elite/.local/lib/python3.7/site-packages/tradedangerous/commands/import_cmd.py", line 122, in run
    if not plugin.run():
  File "/home/elite/.local/lib/python3.7/site-packages/tradedangerous/plugins/eddblink_plug.py", line 945, in run
    if self.downloadFile(SHIPS_URL, self.shipsPath) or self.getOption("force"):
  File "/home/elite/.local/lib/python3.7/site-packages/tradedangerous/plugins/eddblink_plug.py", line 207, in downloadFile
    transfers.download(self.tdenv, url, self.dataPath / path)
  File "/home/elite/.local/lib/python3.7/site-packages/tradedangerous/transfers.py", line 136, in download
    req.raise_for_status()
  File "/home/elite/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/EDCD/coriolis-data/master/dist/index.json
```

**Comment by eyeonus** [comment]
What the heck.

Why did they move it?

**Comment by Tromador** [comment]
Your guess is as good mate.

**Comment by eyeonus** [comment]
They switched to auto-generating that file, so it doesn't exist there anymore. Arg.

**Comment by eyeonus** [comment]
Okay, this is fixed as much as what can be done on our end. You'll need to update the server's TD install.

The next TD update will be just to update the current URL to the new one, so if you use the envar method that update won't be needed for the server:

`SHIPS_URL = os.environ.get('TD_SHIPS') or "https://raw.githubusercontent.com/EDCD/coriolis-data/master/dist/index.json"`
