### ISSUE TITLE
Maintenance thread throws Traceback 

### ISSUE THREAD

**Issue by Tromador** [eyeonus/EDDBlink-listener#24]
Performing server maintenance tasks.2023-04-12 12:18:25.174835
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./eddblink_listener.py", line 632, in process_messages
    db_execute(db, "VACUUM")
NameError: name 'db' is not defined

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/elite/.local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
     self.run()
  File "/home/elite/.local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)                          
 File "./eddblink_listener.py", line 635, in process_messages 
          except Error as e:    
             NameError: name 'Error' is not defined

**Comment by Tromador** [comment]
Other threads are running fine, but as this has locked the DB they can't function. 
I caught it with 4.8GB of memory used in backed up trade schemas it couldn't post.

**Comment by eyeonus** [comment]
Fixed with 7573e65
